---
# tasks file for ovftool

- name: install packages
  sudo: yes
  apt:  name=unzip state=latest
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: get ovftool zip file stats
  stat: path="{{ tmp_dir }}/{{ ovf_zip }}"
  register: ovfzip_stat

- name: Download OVFtool
  get_url:
    url: "{{ ovf_zip_url }}"
    dest: "{{ tmp_dir }}"
  when: (not ovfzip_stat.stat.exists or (ovfzip_stat.stat.md5 != "{{ ovf_zip_md5 }}"))
  register: dload

- name: get ovftool zip file stats
  stat: path="{{ ovf_dir }}/ovftool/ovftool"
  register: ovf_stat

- name: Unzip the OVFtool
  sudo: yes
  unarchive: src="{{ tmp_dir }}/{{ ovf_zip }}" dest="{{ ovf_dir }}" copy=no
  when: dload.changed or (not ovf_stat.stat.exists)

- name: Confirm OVFtool operates
  shell: "{{ ovf_dir }}/ovftool/ovftool --help"
