#vro details:
vro_host_name: 'vro-test1'
vro_ip: '10.112.73.244'
vro_datastore: 'datastore1'
vro_deployment_option: thin
vro_dns: 10.112.64.1
vro_gateway: 10.112.83.253
vro_license_key: 350C5-43J0L-M8V8P-0TLU6
vro_netmask: 255.255.252.0
vro_network: 'VM Network'
vro_root_password: 'VMware1!'

#vro_ova: vRealize-Operations-Manager-Appliance-6.0.2.2777062_OVF10.ova
vro_ova: VMware-vCO-Appliance-6.0.3.0-3000579_OVF10.ova
vro_poweron: '1'
mgmt_vc_username: root
mgmt_vc_password: tupai123
mgmt_vc: "blr-3rd-1-dhcp256.eng.vmware.com"
mgmt_vc_datacenter: 'WDC-Scale-Lab'
mgmt_vc_cluster: 'Scale-Cluster'
vcenter_host: "blr-3rd-1-dhcp256.eng.vmware.com"
vcenter_user: "root"
vcenter_password: "tupai123"
vcenter_port: "443"
esxi_host: "blr-3rd-1-dhcp256.eng.vmware.com"
