---
- hosts: 127.0.0.1
  connection: local
  user: root
  sudo: false
  gather_facts: false
  serial: 1

- name: vRealize Operations Manager alerts and metrices (vCOPS)
  hosts: local
  roles:
    - alerts

